### PR TITLE
Add support for Arch Linux

### PR DESCRIPTION
**Pull request by boppbo**
Hi,

I was able to get enhanced session mode working for arch linux.

For the script it was problematic, that makepkg doesn't work as root. So the user has to enter his password a few times. I tried building the packages with "sudo -u nobody", but makepkg wasn't able to install build dependencies that way. I would appreciate any ideas?

### CODE REVIEW

**Comment by boppbo** [comment]
Sorry, but I don't get the message of the first sentence. Do you mean the ubuntu script should be refactored too, to share more code?

The main difference in config part is the in arch by default missing Xwrapper.config. I already added the modified pam.d config upstream, but don't know when the next release arrives.

**Comment by jterry75** [comment]
@Thaodan - Totally agree with the `config.d` statement. I am going to add an issue to XRDP to at least get it on the radar of something that we could add for a feature. That would be great

@boppbo - I think what @Thaodan is saying is that "If you don't use a single script to accomplish it all you don't have your root problem." IE: Have a makepkg script that can make it from source (but you might not need this if arch already has the built package you wanted). Then have a second script that does the install of the package and configures it. This would enable in the future (with config.d support) the ability to have the "install" script simply add a `config.d/01-xrdp.ini` file that simply starts xrdp with different options. Does that makes sense? 

--

Do you want to separate them before merging if you agree with the above?

**Comment by jterry75** [comment]
[#184](https://github.com/neutrinolabs/xrdp/issues/1084)

**Comment by Thaodan** [comment]
@jterry75  Yes this is exactly what I mean.
But @boppbo  is also right the ubuntu script needs to refactored either by using single script and some includes that mesh the script together before release or by using source.

**Comment by Thaodan** [comment]
I have a script that provides this preprocessor feature for shell script see here:
https://github.com/Thaodan/shpp/blob/master/doc/shpp.org#include

An example is here:
https://github.com/Thaodan/shpp/blob/master/src/tests/include_test.sh

**Comment by jterry75** [comment]
This looks good to me! I will merge when you confirm your ready.

**Comment by boppbo** [comment]
Merge it, please. If there are any further objections they can be handled in a separate issue.

**Pull request merged**
